### ISSUE TITLE
Use more than one dictionary

### ISSUE THREAD

**Issue by KosMos-pv** [CJCombrink/SpellChecker-Plugin#100]
I want to use both Russian and English dictionaries because I often write strings in Russian and comments  in English. But now I can choose only one dictionary at the time. It would be great if there will be an option to add more than one dictionary.

**Comment by CJCombrink** [comment]
Unfortunately I don't think that this will be something that I will look into as one (or at least I) normally use only one dictionary at a time no matter what the application. 
Perhaps you can manually merge two dictionaries by copying the entries from the one into the other, this might work since they are text based (I do not really know how the dictionaries are used or specified but from my limited knowledge it might work)
