### ISSUE TITLE
can't build: strange libraries

### ISSUE THREAD

**Issue by drozel** [CJCombrink/SpellChecker-Plugin#103]
Please help!
I building spellchecker and getting following error at the linkage

`/usr/bin/ld: cannot find -lCore`
`/usr/bin/ld: cannot find -lTextEditor`
`/usr/bin/ld: cannot find -lProjectExplorer`
`/usr/bin/ld: cannot find -lCppEditor`
`/usr/bin/ld: cannot find -lCppTools`
`/usr/bin/ld: cannot find -lKSyntaxHighlighting`
`/usr/bin/ld: cannot find -lAggregation`
`/usr/bin/ld: cannot find -lQtcSsh`
`/usr/bin/ld: cannot find -lCPlusPlus`
`/usr/bin/ld: cannot find -lExtensionSystem`
`/usr/bin/ld: cannot find `-lUtils`

I've installed `libhunspell-1.7-0` and sources and everything described in readme, but i have no idea, which library is meant with `-lKSyntaxHighlighting` etc.

**Comment by Madahin** [comment]
Hello, i was building the plugin "qtcreator-tabbededitor-plugin" and had the exact same linking problem, which lead me to this issue. Since i resolved my problems, i'll try to explain how to fix yours.

to build a qtcreator plugin, you need to have the source and the binary of qtcreator. They need to be pointed by these environment variable : 
```bash
# Look like this on my computer
QTC_BUILD=/usr
QTC_SOURCE=/usr/src/qtcreator
```

you need to be cautious of QTC_BUILD, because qmake will append /lib/qtcreator/plugin to it.

This should solve most of your problems, but KSyntaxHighlighting will still be missing. I had to build it from source and pass to qmake it's location to finally build the plugin i wanted.

you can clone it's source with :
`git clone git://anongit.kde.org/syntax-highlighting.git`

and build it with cmake.

too pass it's location to qmake, you can use these environment variable :
```bash
# Look like this on my computer
KSYNTAXHIGHLIGHTING_INCLUDE_DIR=/usr/local/include/KF5/KSyntaxHighlighting/
KSYNTAXHIGHLIGHTING_LIB_DIR=/usr/lib/
```

You should now be able to build your plugin

**Comment by CJCombrink** [comment]
@Madahin  Thanks for the assistance, it should work as you have described.
To make it easier for my own development look at the "spellchecker_local_paths.pri.example" file and README on how I use it to set up some variables needed by qmake without having to specify them each time when running qmake.
