### ISSUE TITLE
Qt Creator releases using GitHub Actions

### ISSUE THREAD

**Issue by cristianadam** [CJCombrink/SpellChecker-Plugin#110]
Have a look at https://www.qt.io/blog/building-qt-creator-plugins-with-github-actions where I described how you can use GitHub Actions to build a Qt Creator plugin for Linux, mac, and Windows.

**Comment by nocnokneo** [comment]
Another good example: https://github.com/OneMoreGres/qtc-dbviewer/blob/4.13.0/.github/workflows/build.yml

**Comment by CJCombrink** [comment]
@cristianadam @nocnokneo 
I did not forget about this, I am just very busy at the moment (work and personal life).

I am making some good progress, which I could not do without the links that you guys have provided.
If interested, see my "TestGitHubActions" repo. I'm keeping the work separate for now. Will hopefully move the work over here officially later the week.

PS: There are already packages built for Qt Creator 4.13 @ https://github.com/CJCombrink/TestGitHubActions/releases/tag/v4 if anyone is interested and willing/able to test.
I have not tested these yet so anything can happen (I have to re-setup my development machine since I replaced my HDD, decided to try and set up the actions to capture the setup steps needed to build the plugin, working out rather well)

I have definitely not forgotten about the links you guys provided.
Thanks and good luck

**Comment by CJCombrink** [comment]
I created the first GitHub actions powered release, v2.0.7. Please test and perhaps report back if they are working.

I would love to get some feedback on if the MacOS release is working since I do not have a Mac nor access to one.

**Comment by nocnokneo** [comment]
Working fine for me so far. Thanks!

**Comment by cristianadam** [comment]
> 
> I would love to get some feedback on if the MacOS release is working since I do not have a Mac nor access to one.

https://github.com/myspaghetti/macos-virtualbox can help you with a Mac VM.

**Comment by CJCombrink** [comment]
@cristianadam Interesting link thanks, but how legal is this? I do not see any mention of legality of doing this and from my knowledge and a quick google search this looks illegal. Unless told otherwise this is unfortunately not something I can consider.
