### ISSUE TITLE
request: build for QtCreator 10

### ISSUE THREAD

**Issue by bam80** [CJCombrink/SpellChecker-Plugin#143]
The new QtCreator 10 is already out, so corresponding SpellChecker build is needed.
Thanks

**Comment by CJCombrink** [comment]
@bam80 I will do my best to get it fixed tonight. I am really struggling to develop currenlty due to a broken keybord on my laptop, about half the keys does not work thus I code using the part that works and the Windows On-Screen Keyboard. This somewhat puts me off from attempting but due to the release now out I will make it a priority.

**Comment by CJCombrink** [comment]
If you are perhaps on Linux or Mac you could use the builds from here: https://github.com/CJCombrink/SpellChecker-Plugin/actions/runs/4567891966

This issue is holding up the Windows build and as such the release: https://github.com/microsoft/vcpkg/issues/30542
Sorry about that

**Comment by rdnvndr** [comment]
Fix build for QtCreator 10 #144

**Comment by rdnvndr** [comment]
Sorry didn't notice the dev branch feature/qtc10.0

**Comment by CJCombrink** [comment]
@bam80 I have created a release. Please test and close if it works for you.
@rdnvndr Again thank you for your contribution, I saw in your PR that I used the wrong function for my changes.
