### ISSUE TITLE
Any plans to support QtCreator 13

### ISSUE THREAD

**Issue by miemoe** [CJCombrink/SpellChecker-Plugin#156]
Hi,

(it might feel like a deja-vu)

as QtCreator 13 seems to be published soon (RC1 is already available) ...

Are there any plans to adapt the plugin to this new Creator?

Kind regards,
Michael

**Comment by CJCombrink** [comment]
Hi @miemoe 

Yes, I am definitely planning to bring support asap as soon as QtCreator 13 is released. 
I have already started the prep work this side, like building the QtC sources (which takes a bit more than an hour om my laptop)

Thanks for the interest in using the plugin

**Comment by miemoe** [comment]
> Hi @miemoe
> 
> Yes, I am definitely planning to bring support asap as soon as QtCreator 13 is released. I have already started the prep work this side, like building the QtC sources (which takes a bit more than an hour om my laptop)
> 
> Thanks for the interest in using the plugin

Yeah 😁

**Comment by CJCombrink** [comment]
Hi @miemoe 

I saw the announcement thanks, I have set aside time tonight to see how far I can get, so hopefully tonight or soon thereafter.

**Comment by CJCombrink** [comment]
@miemoe 
I made a release, but guess you might have seen.

Please create a new issue if you find any problems. Due to me struggling to get the build in GitHub working I was unable to do my normal 'more extensive' tests. I did some basic testing, all seemed well thus I made the release. Rather have something instead of nothing :P

Again thank you for reaching out.
