### ISSUE TITLE
Detect and ignore urls

### ISSUE THREAD

**Issue by peteristhegreat** [CJCombrink/SpellChecker-Plugin#29]
This plugin is awesome!  Good job.

One minor feature request, to add a custom ignored RegExp such as for a url. `http://...` etc.

**Comment by CJCombrink** [comment]
Thank you,

I am thinking about adding such a feature but if it is only for website urls, try the setting related to websites and see if that does not help.

Websites are difficult since there are so many different options etc in websites. The current RegExp tries its best to remove them but I know it does have a few limitations.
