### ISSUE TITLE
Replace all cases of a misspelled word

### ISSUE THREAD

**Issue by JPNaude** [CJCombrink/SpellChecker-Plugin#32]
When the same word is misspelled in multiple places, would be nice if you can replace all in current file, and replace all in current project etc.

**Comment by CJCombrink** [comment]
The "Give Suggestions" dialog gives the option to replace all in the current file.

Also a setting in the options page can be set to replace all occurrences in the current file from the list of suggestions in the right click menu.

Closing the issue since replacing all in the current project is not planned for now.
