### ISSUE TITLE
Q: Why do you parse the source by yourself?

### ISSUE THREAD

**Issue by firegurafiku** [CJCombrink/SpellChecker-Plugin#40]
AFAIK, Qt Creator uses Kate editor syntax highlighting definitions which have semantic distinction for various parts of language syntax. To my mind, you should rely on that definitions instead of your own parsing, this will also make your plugin language-independent.

For example, then you have highlighted file open in the editor, you should find all code blocks marked as "comment" by syntactic highlighter and then check them. Why do you need your own parser at all? Qt Creater API provides you a way to access its highlighting information, or not?

**Comment by CJCombrink** [comment]
Hi, 

I do not fully understand your question but I will try to answer: "you should find all code blocks marked as "comment" by syntactic highlighter and then check them". This is exactly what I am doing. The reason for the CppParser is because in QtCreator there are many classes for the different document types. QtC has a cppeditor, texteditor, qmljseditor, etc. So the reason I have the CppParser is because it works on the CppEditor and gives me the flexibility to add more editors, like for qml documents etc.

I then call the function "CPlusPlus::TranslationUnit::commentAt()" to get the comment. Then I work with the comment block and extract words by creating tokens from each word based on the settings that the user supplied. There are other libraries that can do this part as well, I investigated one such but it was a bit limiting and added some dependencies that I did not want to add so I decided to challenge myself to see if I can not get it done.

As far as I am aware (or at the time of implementation) there was no generic or default base class that had the same functionality for all types of editors in QtC. As you can see in the above paragraph, the "commentAt()" function is part of the CPlusPlus plugin, so to use the same function on the qml or other editors does not give the expected result in all cases, that is the reason why I restrict it to C++ (and coming C).

I will spend some time looking at this again and perhaps there is a more generic way to do this.

**Comment by firegurafiku** [comment]
@CJCombrink 

Oh, sorry about bothering you and thanks for that detailed response. I thought you have reinvented the *whole* C++ parsing, which I'd regard as a terrible idea. I'm so glad that's not the case.
