### ISSUE TITLE
Not working with QtCreator 4.2.82

### ISSUE THREAD

**Issue by thk123** [CJCombrink/SpellChecker-Plugin#60]
When I install the plugin, on starting QtCreator I get the following errors:

```
Could not resolve dependency 'Core(4.2.0)'
Could not resolve dependency 'TextEditor(4.2.0)'
Could not resolve dependency 'ProjectExplorer(4.2.0)'
Could not resolve dependency 'CppEditor(4.2.0)'
Could not resolve dependency 'CppTools(4.2.0)'
```

I don't know if this is because I am using 4.2.82 and you need to do a separate release for each point release or if I've done something else wrong. 

```
$ hunspell --version
@(#) International Ispell Version 3.2.06 (but really Hunspell 1.3.3)
```

**Comment by CJCombrink** [comment]
I am assuming that you are building QtCreator yourself? If yes, against which branch/tag of QtC are you building?

Normally QtC should handle 4.2.X with the listed dependencies, not sure why .82 would be a problem. Unless QtC is specifically handling that version. From my understanding such a version is a development number, like alpha or beta number.

(sorry at this moment I can't help, just trying to get some more information)

**Comment by thk123** [comment]
Thanks for the quick reply! I am not compiling my own version of QtCreator, but I am using [this PPA](https://launchpad.net/~adrozdoff/+archive/ubuntu/qtcreator-git) to get a more up-to-date version (as Ubuntu 16.04 was only getting 3.4).

**Comment by CJCombrink** [comment]
Ok the problem is the version of Qt Creator that you have. 
If you look at say a normal/released QtCreator PRI file you see the API compatibility number is the base release:
So for QtC 4.2.1 it is set to 4.2.0: http://code.qt.io/cgit/qt-creator/qt-creator.git/tree/qtcreator.pri?h=v4.2.1#n4
Thus Qt Creator 4.2.1 can load plugin from version 4.2.0 and higher, up to 4.2.1

If you look at the master (which you have) the compat version is set to 4.2.82, thus QtCreator will not accept the plugin since it will only accept plugins with the version at least as high as compat version: 
http://code.qt.io/cgit/qt-creator/qt-creator.git/tree/qtcreator.pri#n4

Unfortunately you will not be able to use the plugin with that version of QtC.

**Comment by thk123** [comment]
So I installed 4.2.1 by running the QtCreator installer and that works correctly. Thanks for your (rapid) help.
