### ISSUE TITLE
Does not load with Qt Creator 4.6.1 on Linux

### ISSUE THREAD

**Issue by moberhuber** [CJCombrink/SpellChecker-Plugin#89]
Qt creator 4.6.1 was just released:
http://blog.qt.io/blog/2018/05/03/qt-creator-4-6-1-released/

The SpellCheckerPlugin fails to load, seems due to a breaking change in Core::IOptionsPage :
`qtcreator-4.6.1/bin/qtcreator: symbol lookup error: /home/tobi/work/ognix/Source/build/qtcreator/qtcreator-4.6.1/lib/qtcreator/plugins/libSpellChecker.so: undefined symbol: _ZN4Core12IOptionsPageC2EP7QObject`

**Comment by patplan** [comment]
... same on Windows...

**Comment by CJCombrink** [comment]
@moberhuber @patplan 
I am aware of that, please look at the release page, I have uploaded new binaries to the previous release specifically for QtC 4.6.1

I will still try to get a binary uploaded for Ubuntu 16.04 but could not get a chance yet to download the image so that I can set up my VM. 

Out of curiosity, what OS are you using mostly when using the plugin?

I think the QtCreator guys slipped up on this one, not sure if my plugin is the only one with this problem or if it is a broader issue.

**Comment by CJCombrink** [comment]
I have uploaded a build of the plugin that should work on Ubuntu 16.04 x64.

**Comment by patplan** [comment]
Thanks! It works for me... (win 10 x64; QtCreator x86)
